import requests
import base64
import os
import time

# =====================================================================
# Configuration
# =====================================================================
# If Wan2GP is running via localtunnel in Colab, put your ngrok or localtunnel URL here
# Example: "https://my-colab-url.loca.lt"
API_BASE_URL = "http://127.0.0.1:8000"

OUTPUT_DIR = "client_outputs"

# =====================================================================
# Setup
# =====================================================================
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

def save_base64_to_file(base64_string, filename):
    """Utility to save a base64 string to a file on your local PC."""
    output_path = os.path.join(OUTPUT_DIR, filename)
    with open(output_path, "wb") as f:
        f.write(base64.b64decode(base64_string))
    print(f"[SUCCESS] Saved file locally to: {output_path}")
    return output_path

# =====================================================================
# Pipeline Example
# =====================================================================

def run_pipeline():
    print(f"--- Ensuring API is reachable at {API_BASE_URL} ---")
    try:
        response = requests.get(f"{API_BASE_URL}/docs")
        if response.status_code == 200:
            print("Server is accessible!")
    except Exception as e:
        print(f"Error reaching server: {e}")
        print("Please check your API_BASE_URL and make sure the server is running.")
        return

    # 1. Image Generation (Flux)
    print("\n--- Starting Phase 1: Flux Image Generation ---")
    
    # You can customize these arguments
    flux_payload = {
        "prompt": "A majestic golden lion standing on a cliff at sunset, highly detailed, photorealistic",
        "resolution": "1024x1024",
        "steps": 25,
        "guidance_scale": 3.5,
        "seed": -1,
        # Example using LoRA (ensure path is correct on the server/Colab!)
        # "loras": [{"path": "/path/to/my_lion_lora.safetensors", "multiplier": 0.8}]
    }

    print("Sending request to /api/generate/flux...")
    start_time = time.time()
    res = requests.post(f"{API_BASE_URL}/api/generate/flux", json=flux_payload)
    
    if res.status_code != 200:
        print(f"[ERROR] Flux generation failed: {res.text}")
        return

    result_json = res.json()
    flux_server_path = result_json.get("file_path") 
    flux_b64 = result_json.get("file_data_base64")
    
    # Save the file locally
    local_image_path = save_base64_to_file(flux_b64, f"flux_result_{int(time.time())}.png")
    print(f"Phase 1 complete in {time.time() - start_time:.1f}s.")
    print(f"The file is saved on the server at: {flux_server_path}")

    # 2. Video Generation (LTX)
    print("\n--- Starting Phase 2: LTX Video Generation ---")
    print(f"Using {flux_server_path} (from the server) as the starting frame...")

    ltx_payload = {
        "prompt": "The majestic golden lion roars, wind blowing through its mane, slow motion, highly detailed",
        "image_start": flux_server_path, # Provide the path generated by Step 1!
        "resolution": "1280x720",
        "steps": 30,
        "guidance_scale": 3.0,
        "seed": -1,
        "video_length": 97
    }

    print("Sending request to /api/generate/video...")
    start_time = time.time()
    res = requests.post(f"{API_BASE_URL}/api/generate/video", json=ltx_payload)

    if res.status_code != 200:
        print(f"[ERROR] Video generation failed: {res.text}")
        return

    result_json = res.json()
    video_b64 = result_json.get("file_data_base64")
    
    # Save the file locally
    save_base64_to_file(video_b64, f"ltx_result_{int(time.time())}.mp4")
    print(f"Phase 2 complete in {time.time() - start_time:.1f}s.")

if __name__ == "__main__":
    run_pipeline()
